apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-cicd-app
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: my-cicd-app:latest
